use std::io::{self, Write};
use crate::geom::{Point2, Polygon2, Segment2};

pub struct PrintConfig {
    pub nozzle_temp: u32,
    pub bed_temp: u32,
    pub layer_height: f64,
    pub line_width: f64,
    pub filament_diameter: f64,
    pub print_speed_perimeter: f64, // mm/s
    pub print_speed_infill: f64,    // mm/s
    pub travel_speed: f64,          // mm/s
    pub retract_dist: f64,          // mm
    pub retract_speed: f64,         // mm/s
}

impl Default for PrintConfig {
    fn default() -> Self {
        Self {
            nozzle_temp: 210,
            bed_temp: 60,
            layer_height: 0.20,
            line_width: 0.45,
            filament_diameter: 1.75,
            print_speed_perimeter: 45.0,
            print_speed_infill: 60.0,
            travel_speed: 150.0,
            retract_dist: 0.8,
            retract_speed: 35.0,
        }
    }
}

pub struct ProcessedLayer {
    pub layer_index: usize,
    pub z: f64,
    pub perimeters: Vec<Vec<Polygon2>>, // per-contour perimeter loops
    pub infill: Vec<Segment2>,
}

pub struct GCodeWriter<'a> {
    config: &'a PrintConfig,
    current_pos: Point2,
    is_retracted: bool,
    filament_area: f64,
}

impl<'a> GCodeWriter<'a> {
    pub fn new(config: &'a PrintConfig) -> Self {
        let r = config.filament_diameter * 0.5;
        let filament_area = std::f64::consts::PI * r * r;
        Self {
            config,
            current_pos: Point2::new(0.0, 0.0),
            is_retracted: false,
            filament_area,
        }
    }

    pub fn write_gcode<W: Write>(
        &mut self,
        writer: &mut W,
        layers: &[ProcessedLayer],
    ) -> io::Result<()> {
        self.write_header(writer)?;

        for layer in layers {
            self.write_layer(writer, layer)?;
        }

        self.write_footer(writer)?;
        Ok(())
    }

    fn write_header<W: Write>(&mut self, w: &mut W) -> io::Result<()> {
        writeln!(w, "; Generated by Tetanus-Slicer")?;
        writeln!(w, "; Fast standalone slicing engine written in Rust")?;
        writeln!(w, "G21 ; metric values")?;
        writeln!(w, "G90 ; absolute positioning")?;
        writeln!(w, "M83 ; use relative extrusion distances")?;
        writeln!(w, "M104 S{} ; set nozzle temp", self.config.nozzle_temp)?;
        writeln!(w, "M140 S{} ; set bed temp", self.config.bed_temp)?;
        writeln!(w, "M190 S{} ; wait for bed temp", self.config.bed_temp)?;
        writeln!(w, "M109 S{} ; wait for nozzle temp", self.config.nozzle_temp)?;
        writeln!(w, "G28 ; home all axes")?;
        writeln!(w, "G92 E0 ; reset extruder")?;
        writeln!(w, "; Prime line")?;
        writeln!(w, "G1 Z0.3 F1000")?;
        writeln!(w, "G1 X10 Y10 F{}", self.config.travel_speed * 60.0)?;
        writeln!(w, "G1 X100 E8.0 F1200")?;
        writeln!(w, "G1 X100 Y10.5 F{}", self.config.travel_speed * 60.0)?;
        writeln!(w, "G1 X10 E16.0 F1200")?;
        writeln!(w, "G92 E0")?;
        Ok(())
    }

    fn write_layer<W: Write>(&mut self, w: &mut W, layer: &ProcessedLayer) -> io::Result<()> {
        writeln!(w, "\n; ---------------------------------")?;
        writeln!(
            w,
            "; LAYER: {} | Z = {:.3}",
            layer.layer_index, layer.z
        )?;
        writeln!(w, "; ---------------------------------")?;

        // Move to layer height
        writeln!(w, "G1 Z{:.3} F{}", layer.z, self.config.travel_speed * 60.0)?;

        let perimeter_feedrate = self.config.print_speed_perimeter * 60.0;
        let infill_feedrate = self.config.print_speed_infill * 60.0;

        // 1. Perimeters
        for contour_perimeters in &layer.perimeters {
            for poly in contour_perimeters {
                if poly.points.len() < 2 {
                    continue;
                }

                // Travel to start of polygon
                self.travel_to(w, poly.points[0])?;

                // Trace polygon edges with extrusion
                let n = poly.points.len();
                for i in 0..n {
                    let next_pt = poly.points[(i + 1) % n];
                    let dist = self.current_pos.distance_to(next_pt);
                    let e = self.calculate_e(dist);
                    writeln!(
                        w,
                        "G1 X{:.3} Y{:.3} E{:.4} F{:.1}",
                        next_pt.x, next_pt.y, e, perimeter_feedrate
                    )?;
                    self.current_pos = next_pt;
                }
            }
        }

        // 2. Infill
        if !layer.infill.is_empty() {
            writeln!(w, "; Infill")?;
            for seg in &layer.infill {
                self.travel_to(w, seg.p1)?;
                let dist = seg.length();
                let e = self.calculate_e(dist);
                writeln!(
                    w,
                    "G1 X{:.3} Y{:.3} E{:.4} F{:.1}",
                    seg.p2.x, seg.p2.y, e, infill_feedrate
                )?;
                self.current_pos = seg.p2;
            }
        }

        Ok(())
    }

    fn travel_to<W: Write>(&mut self, w: &mut W, target: Point2) -> io::Result<()> {
        if self.current_pos.distance_to(target) < 1e-4 {
            return Ok(());
        }

        // Retract before travel
        if !self.is_retracted && self.config.retract_dist > 0.0 {
            writeln!(
                w,
                "G1 E-{:.2} F{:.1}",
                self.config.retract_dist,
                self.config.retract_speed * 60.0
            )?;
            self.is_retracted = true;
        }

        // Travel move
        writeln!(
            w,
            "G1 X{:.3} Y{:.3} F{:.1}",
            target.x,
            target.y,
            self.config.travel_speed * 60.0
        )?;
        self.current_pos = target;

        // Unretract upon arrival
        if self.is_retracted && self.config.retract_dist > 0.0 {
            writeln!(
                w,
                "G1 E{:.2} F{:.1}",
                self.config.retract_dist,
                self.config.retract_speed * 60.0
            )?;
            self.is_retracted = false;
        }

        Ok(())
    }

    fn calculate_e(&self, dist: f64) -> f64 {
        let bead_volume = dist * self.config.line_width * self.config.layer_height;
        bead_volume / self.filament_area
    }

    fn write_footer<W: Write>(&mut self, w: &mut W) -> io::Result<()> {
        writeln!(w, "\n; End G-code")?;
        writeln!(w, "M104 S0 ; turn off nozzle")?;
        writeln!(w, "M140 S0 ; turn off bed")?;
        writeln!(w, "G91 ; relative positioning")?;
        writeln!(w, "G1 E-2 F1800 ; retract filament")?;
        writeln!(w, "G1 Z10 F3000 ; lift nozzle")?;
        writeln!(w, "G90 ; absolute positioning")?;
        writeln!(w, "G28 X0 Y0 ; home X and Y")?;
        writeln!(w, "M84 ; disable motors")?;
        Ok(())
    }
}
